import logo from "@/app/assets/logo.png";
import { Heading } from "@radix-ui/themes";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout() {
    return (
        <>
            <div className="w-full h-screen bg-blue-100 flex justify-center items-center">
                <div className="flex flex-col gap-5 p-8 bg-white w-full sm:max-w-md rounded-md">
                    <Image src={logo} width={200} alt="Logo" />
                    <Heading as="h1" size="8">Boutique</Heading>
                    <div className="flex flex-col gap-5">
                        <input type="text" />
                    </div>
                </div>
            </div>
        </>
    );
}
